Added typings
wzhouwzhou/ytsearcher pull request #5
Opened 2021-03-25 16:11 UTC by Lioness100

2021-03-28 02:39 UTC, wzhouwzhou approved these changes
LGTM, thanks!

2021-03-28 02:40 UTC, Vetlix approved these changes
very good, looking back, very bad

2021-03-28 02:44 UTC, wzhouwzhou commented on index.d.ts
> +  public totalResult?: number | null;
Actually, I'm not sure if the searcher itself has a totalResult

2021-03-28 02:45 UTC, tbnritzdoge commented
should consider having consistent code and actual strict typings instead of unknowns everywhere. ngtm.

2021-03-28 02:45 UTC, wzhouwzhou commented on index.d.ts
> +  public prevPageToken?: string;
Page tokens appear in the YTSearch, not the searcher

2021-03-28 02:49 UTC, tbnritzdoge requested changes

2021-03-28 02:49 UTC, tbnritzdoge commented on index.d.ts
> +export type Options = Record<string, unknown>;
Why not strictly type this so the user actually knows which options are valid and what value they provide for said key

2021-03-28 02:49 UTC, tbnritzdoge commented on index.d.ts
> +  public search(options?: Record<string, unknown>, apiKey?: KeyData): Promise<this>;
consistency?

2021-03-28 03:03 UTC, Vetlix commented on index.d.ts
> +export type Options = Record<string, unknown>;
Please make the options correspond with this: https://developers.google.com/youtube/v3/docs/search/list

2021-03-28 13:03 UTC, Vetlix commented on index.d.ts
> +interface SearchOptions {
Maybe export these just in case someone might need them?

2021-03-28 21:02 UTC, diced approved these changes

2021-03-29 02:59 UTC, wzhouwzhou commented
@tbnritzdoge How's it looking now?

2021-03-29 03:00 UTC, tbnritzdoge approved these changes
Much better, thanks for the improvements. LGTM :)

2021-03-29 03:02 UTC, merged

2021-03-29 03:03 UTC, wzhouwzhou commented
Thanks all