add syntacx highliht
wzhouwzhou/ytsearcher pull request #7
Opened 2021-03-30 04:52 UTC by diced

2021-03-30 04:52 UTC, advilm approved these changes

2021-03-30 04:53 UTC, rpxs commented
no

2021-03-30 04:54 UTC, rpxs commented
Messed up the indent

2021-03-30 04:54 UTC, wzhouwzhou requested changes

2021-03-30 04:54 UTC, wzhouwzhou commented on README.md
> +const { apiurl } = require('ytsearcher');
Would be careful about the indentation here

2021-03-30 04:54 UTC, wzhouwzhou commented on README.md
> +const { validOptions } = require('ytsearcher');
Above comment; indentation applies here as well

2021-03-30 04:56 UTC, diced commented
remember this commit fixes your dogwater md syntax

2021-03-30 04:57 UTC, rpxs commented
who asked

2021-03-30 04:57 UTC, diced commented
> who asked

you're wrong your mom asked

2021-03-30 04:57 UTC, rpxs commented
ok you got me there

2021-03-30 04:58 UTC, wzhouwzhou requested changes

2021-03-30 04:58 UTC, wzhouwzhou commented on README.md
> +ytsearcher.search(QUERY, { type: 'video' })
Let's put the `.then`'s on the same line for style purposes

2021-03-30 04:58 UTC, diced commented
mad bc u bad

2021-03-30 04:58 UTC, rpxs requested changes
Fix indents, all good.

2021-03-30 05:01 UTC, diced commented
ok is this good

2021-03-30 05:02 UTC, rpxs approved these changes

2021-03-30 05:03 UTC, diced commented
U Snooze U Lose

2021-03-30 05:04 UTC, wzhouwzhou requested changes
Let's also change over the badge to be latest, and update references to 2.5 KB to now be 2.2 KB as per https://bundlephobia.com/result?p=ytsearcher@1.2.4

2021-03-30 05:09 UTC, diced commented
god you are so needy

2021-03-30 05:58 UTC, wzhouwzhou approved these changes
LGTM now!

2021-03-30 18:29 UTC, Vetlix approved these changes
merge!!

2021-03-30 20:57 UTC, rpxs reviewed
pogger commit

2021-03-30 20:58 UTC, rpxs approved these changes

2021-03-30 20:58 UTC, rpxs commented
pressed wrong button so i only review instead of approve but it works now

2021-03-30 23:57 UTC, diced commented
@wzhouwzhou merg

2021-03-31 02:45 UTC, tbnritzdoge approved these changes
these changes are critical to the future of the NODE.JAVASCRIPT developr enviorment and must be merged with no delay!!

2021-03-31 03:03 UTC, rpxs approved these changes
didnt end up eating taco bell today ☹️ ☹️ instead had mango juice 😃

2021-03-31 03:34 UTC, merged

2021-03-31 04:52 UTC, rpxs commented
poggers!

2021-03-31 18:34 UTC, advilm commented
mango juice op